@baseURL=http://127.0.0.1:5000
@recaptchaResponse=demo

### @name Login
POST {{baseURL}}/login HTTP/1.1
Accept: application/json
Content-Type: application/json
x-recaptcha-response: {{recaptchaResponse}}

{
  "username": "testuser",
  "password": "testpassword"
}

### @name ByPass
GET {{baseURL}}/bypass HTTP/1.1
Accept: application/json
